name: Android Release

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  assembleRelease:
    runs-on: ubuntu-22.04

    container:
      image: cirrusci/flutter:3.3.6

    steps:
      - uses: actions/checkout@v2
      - name: Restore Release Keystore from secrets
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" --batch release.keystore.asc > android/app/release.keystore
      - name: Install dependencies
        run: flutter pub get
      - name: Create Appbundle
        run: flutter build appbundle --release
        env:
          ANDROID_RELEASE_ALIAS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS }}
          ANDROID_RELEASE_ALIAS_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS_PASSWORD }}
          ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_STORE_PASSWORD }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
      - name: Load google_play_service_account.json from secrets
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > google_play_service_account.json
      - name: Upload to GooglePlay
        uses: r0adkll/upload-google-play@v1.0.19
        if: startsWith(github.ref, 'refs/tags/')
        # workaround, see https://github.com/r0adkll/upload-google-play/issues/129#issuecomment-1325892395
        env:
          OPENSSL_CONF: /dev/null
        with:
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJson: google_play_service_account.json
          packageName: com.munichways.app
          track: alpha
          status: completed
