name: Android Release

on:
  push:
    tags:
      - '*'

jobs:
  assembleRelease:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:2.8.1
      
    steps:
      - uses: actions/checkout@v2
      - name: Restore Release Keystore from secrets
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" --batch release.keystore.asc > android/app/release.keystore
      - name: Install dependencies
        run: flutter pub get
      - name: Create Appbundle
        run: flutter build appbundle --release
        env:
          ANDROID_RELEASE_ALIAS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS }}
          ANDROID_RELEASE_ALIAS_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS_PASSWORD }}
          ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_STORE_PASSWORD }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      - name: Create APK
        run: flutter build apk --release
        env:
          ANDROID_RELEASE_ALIAS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS }}
          ANDROID_RELEASE_ALIAS_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_ALIAS_PASSWORD }}
          ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_STORE_PASSWORD }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/apk/release
      - uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      
      
