name: Pull Request Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:3.32.8

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Check Formatting
        run: dart format --set-exit-if-changed .
      - name: Static code analyse
        run: flutter analyze .
