name: Pull Request Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
      - name: Set up Java
        uses: actions/setup-java@v6.0.1
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.6'
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Static code analyse
        run: flutter analyze .
      - name: Run tests
        run: flutter test
